export const APPLICANT_IDENTIFIED_EVENT = "APPLICANT_IDENTIFIED_EVENT";
export const FRAUD_APPROVED_EVENT = "FRAUD_APPROVED_EVENT";
export const FRAUD_DECLINED_EVENT = "FRAUD_DECLINED_EVENT";
export const CREDIT_APPROVED_EVENT = "CREDIT_APPROVED_EVENT";
export const CREDIT_DECLINED_EVENT = "CREDIT_DECLINED_EVENT";