export const APPLICATION_APPLICANT_IDENTIFIED_EVENT = "APPLICATION_APPLICANT_IDENTIFIED_EVENT";
export const APPLICATION_FRAUD_APPROVED_EVENT = "APPLICATION_FRAUD_APPROVED_EVENT";
export const APPLICATION_FRAUD_DECLINED_EVENT = "APPLICATION_FRAUD_DECLINED_EVENT";
export const APPLICATION_CREDIT_APPROVED_EVENT = "APPLICATION_CREDIT_APPROVED_EVENT";
export const APPLICATION_CREDIT_DECLINED_EVENT = "APPLICATION_CREDIT_DECLINED_EVENT";

export const APPLICATION_SUBMITTED_EVENT = "APPLICATION_SUBMITTED_EVENT";
export const APPLICATION_APPROVED_EVENT = "APPLICATION_APPROVED_EVENT";
export const APPLICATION_DECLINED_EVENT = "APPLICATION_APPROVED_EVENT";